# Generated by Django 5.2.10 on 2026-01-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_location_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_reunited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AddField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
