# Generated by Django 5.2.10 on 2026-01-24 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_announcement_is_reunited_announcement_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='microchip_id',
        ),
    ]
