# Generated by Django 5.2.10 on 2026-01-24 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pet_microchip_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='phone_number',
            new_name='contact_phone',
        ),
    ]
