# Generated by Django 5.2.10 on 2026-02-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='contact_phone',
        ),
    ]
