# Generated by Django 5.2.10 on 2026-02-24 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reaction',
            name='unique_reaction_per_user_announcement_kind',
        ),
        migrations.AddField(
            model_name='reaction',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.comment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New message'), ('post_saved', 'Post saved'), ('post_liked', 'Post liked'), ('contacted', 'Contacted'), ('comment_on_announcement', 'Comment on announcement'), ('comment_reaction', 'Reaction on comment'), ('post_reacted', 'Announcement reacted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.announcement'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('comment__isnull', False)), fields=('user', 'comment'), name='unique_reaction_per_user_comment'),
        ),
        migrations.AddConstraint(
            model_name='reaction',
            constraint=models.UniqueConstraint(condition=models.Q(('announcement__isnull', False)), fields=('user', 'announcement', 'kind'), name='unique_reaction_per_user_announcement_kind'),
        ),
    ]
