# Generated by Django 5.2.10 on 2026-02-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_reaction_unique_reaction_per_user_announcement_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='kind',
            field=models.CharField(max_length=191),
        ),
    ]
