# Generated by Django 5.2.10 on 2026-02-24 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_reaction_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New message'), ('post_saved', 'Post saved'), ('post_liked', 'Post liked'), ('contacted', 'Contacted'), ('comment_on_announcement', 'Comment on announcement'), ('comment_reaction', 'Reaction on comment'), ('post_reacted', 'Announcement reacted'), ('possible_match', 'Possible match')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='kind',
            field=models.CharField(choices=[('like', 'Like'), ('helpful', 'Helpful')], max_length=20),
        ),
    ]
