# Generated by Django 5.2.10 on 2026-03-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification_actor_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='kind',
            field=models.CharField(choices=[('like', 'Like'), ('helpful', 'Helpful'), ('sad', 'Sad'), ('laugh', 'Laugh'), ('angry', 'Angry'), ('surprised', 'Surprised'), ('love', 'Love')], max_length=20),
        ),
    ]
