# Generated by Django 5.2.10 on 2026-03-04 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_chatmessagereaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New message'), ('post_saved', 'Post saved'), ('post_liked', 'Post liked'), ('contacted', 'Contacted'), ('comment_on_announcement', 'Comment on announcement'), ('comment_reaction', 'Reaction on comment'), ('post_reacted', 'Announcement reacted'), ('possible_match', 'Possible match'), ('subscription_alert', 'Subscription alert')], max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('radius_m', models.FloatField(default=5000.0)),
                ('keywords', models.CharField(blank=True, default='', max_length=300)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
