# Generated by Django 5.2.10 on 2026-03-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_notification_type_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='search_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New message'), ('post_saved', 'Post saved'), ('post_liked', 'Post liked'), ('contacted', 'Contacted'), ('comment_on_announcement', 'Comment on announcement'), ('comment_reaction', 'Reaction on comment'), ('post_reacted', 'Announcement reacted'), ('possible_match', 'Possible match')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
