# Generated by Django 5.2.10 on 2026-03-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_location_search_radius_alter_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alert_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alert_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='alerts_radius',
            field=models.FloatField(blank=True, help_text='Preferred radius in meters for nearby alerts', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_message', 'New message'), ('post_saved', 'Post saved'), ('post_liked', 'Post liked'), ('contacted', 'Contacted'), ('comment_on_announcement', 'Comment on announcement'), ('comment_reaction', 'Reaction on comment'), ('post_reacted', 'Announcement reacted'), ('possible_match', 'Possible match'), ('nearby_alert', 'Nearby alert')], max_length=50),
        ),
    ]
